# Generated by Django 5.2.5 on 2025-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileanalysis',
            name='score',
            field=models.TextField(),
        ),
    ]
