# Generated by Django 5.2.5 on 2026-03-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_jobpost_jobapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requirement_snapshot", models.TextField()),
                ("github_username", models.CharField(max_length=100)),
                ("github_summary", models.TextField()),
                ("score", models.TextField()),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("recommendations", models.TextField()),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                ("application", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation", to="dashboard.jobapplication")),
            ],
        ),
    ]
