# Generated by Django 5.2.5 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_jobapplicationevaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="github_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_file",
            field=models.FileField(blank=True, upload_to="job_applications/resumes/"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_text",
            field=models.TextField(blank=True),
        ),
    ]
